---
- name: Converge
  hosts: all
  serial: 1
  tasks:
    - name: Wait for ES to be reachable from this container
      ansible.builtin.uri:
        url: "http://elasticsearch-test:9200/_cluster/health"
        method: GET
        status_code: 200
      register: elastalert2_es_check
      retries: 30
      delay: 5
      until: elastalert2_es_check.status == 200

    - name: Include elastalert2 role
      ansible.builtin.include_role:
        name: boutetnico.elastalert2
      vars:
        elastalert2_elasticsearch_host: elasticsearch-test
        elastalert2_rules:
          - name: "Test rule"
            type: any
            index: "test-*"
            timestamp_field: "@timestamp"
            filter:
              - query:
                  query_string:
                    query: "level:error"
            realert:
              minutes: 1
            alert:
              - debug
